### ISSUE TITLE
Lahoda 2008 is not working properly

### ISSUE THREAD

**Issue by ghost** [paiv/latynka#1]
Hi. Thanks for the excellent project! I tried all of the versions, but the Lahoda 2008 is showing webpages with diacritics in incorrect  places. I attach a screenshot of a website where this is visible. It would be great if you could try to fix it. Best! Hryćko.

<img width="1221" alt="screenshot 2017-11-17 21 12 57" src="https://user-images.githubusercontent.com/33765124/32969253-4268b2b6-cbdc-11e7-84c1-0c00e5b7268b.png">
<img width="1347" alt="screenshot 2017-11-17 21 13 26" src="https://user-images.githubusercontent.com/33765124/32969256-473b70b2-cbdc-11e7-80e0-c65d10f26954.png">

**Comment by paiv** [comment]
This is the known issue of fonts on a page not handling Unicode.

Specifically for pravda.com.ua there is a newer version of a font they use that renders Unicode properly.

-----

Diving into details, there are two ways to render a letter with diacritic:
a) use a precomposed character: š (`\u0161`)
b) use a base character with combining diacritic: š (`\u0073\u030c`)

Modern Unicode recommends b), since number of precomposed a) characters is limited.

Back to fonts, some of them could not handle precomposed characters, like
<img width="181" alt="1" src="https://user-images.githubusercontent.com/196601/32972749-8f6e2a1c-cbfc-11e7-83b0-5afb5e7e1257.png">
(here a different font is used by browser to render diacritics)

Even more fonts could not handle combining diacritics, like on your screenshots.

Browser's rendering engine tries to compensate font deficiencies. End result is different for different browsers.

In the **latynka** extension you can find two tables – `Nova Latynka` and `Nova Latynka alt` that uses a) and b) approaches to diacritics for comparison.

----

The Lahoda's approach is packed with diacritics. The `Lahoda` table currently is using combining characters. We can change the table to use precomposed characters, but the result is still depends on the font. As you've seen on pravda.com.ua the font have issues with precomposed characters too.

**Comment by paiv** [comment]
Here is the `Lahoda` table with precomposed characters only:
https://git.io/vF9cb

**Comment by ghost** [comment]
Hi! I forgot to say 'thanks' last time. I managed to play around with it and it works well. BTW, I'm now using Псевдо-Їречківка, which makes things look good. Appears to follow very similar rules to the best existing eastern slavic latin alphabet, Belarusian '[Lacinka](https://en.wikipedia.org/wiki/Belarusian_Latin_alphabet)'. Best wishes.

**Comment by paiv** [comment]
Updated Lahoda for precomposed characters in 0.8.5 7dca724

Note that same could not be done for ISO 9:1995 since there is no precomposed characters for `g̀ g\u0300 l̀ l\u0300` etc.
